# Generated by Django 2.1 on 2018-08-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_questionaire_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlink',
            name='answer',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='', max_length=2048),
        ),
    ]
