# Generated by Django 2.1 on 2018-08-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180821_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionlink',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('binary', 'binary')], default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionlink',
            name='answer',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
